In [7]:
import numpy as np
a = np.array(
                [
                    [1,2],
                    [3,4]
                ]
            )
print('First Array:')
print(a)
print('\n')
b = np.array(
                [
                    [5,6],
                    [7,8]
                ]
            )
print('Second Array:')
print(b)
print('\n')
print('Stack the two arrays along axis 0')
print(np.stack((a,b),0)) 

print('\nStack the two arrays along axis 1')
print(np.stack((a,b),1))


First Array:
[[1 2]
 [3 4]]


Second Array:
[[5 6]
 [7 8]]


Stack the two arrays along axis 0
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Stack the two arrays along axis 1
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [8]:
print(np.stack((a,b)))  # Default stacking

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
